---
- name: install packages with homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - ack
    - brew-cask
    - fasd
    - leiningen
    - node
    - reattach-to-user-namespace
    - tmux
    - vim
    - wget

- name: install oh-my-zsh
  shell: "wget --no-check-certificate http://install.ohmyz.sh -O - | sh"
  args:
    chdir: "{{ home }}"
    creates: "{{ home }}/.oh-my-zsh"

- name: install apps with brew cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - alfred
    - atom
    - dropbox
    - google-chrome
    - iterm2
    - karabiner
    - seil
    - slack
    - spotify
    - vagrant
    - virtualbox

- name: install vundle
  git:
    repo: https://github.com/gmarik/Vundle.vim.git
    dest: "{{ home }}/.vim/bundle/Vundle.vim"

- name: fetch dotfiles
  git:
    repo: https://github.com/joaalto/dotfiles-mac
    dest: "{{ home }}/dotfiles-mac"

- name: create links to dotfiles
  file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
      - { src: "~/dotfiles-mac/.lein/profiles.clj", dest: "~/.lein/profiles.clj" }
      - { src: "~/dotfiles-mac/.vimrc", dest: "~/.vimrc" }
      - { src: "~/dotfiles-mac/.gitconfig", dest: "~/.gitconfig" }
      - { src: "~/dotfiles-mac/.gitignore_global", dest: "~/.gitignore_global" }

