---

- name: install packages with homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - ack
    - brew-cask
    - fasd
    - git
    - leiningen
    - node
    - reattach-to-user-namespace
    - tmux
    - vim
    - wget

- name: install oh-my-zsh
  shell: "wget --no-check-certificate http://install.ohmyz.sh -O - | sh"
  args:
    chdir: "{{ home }}"
    creates: "{{ home }}/.oh-my-zsh"

- name: install apps with brew cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - alfred
    - atom
    - dropbox
    - google-chrome
    - iterm2
    - karabiner
    - slack
    - spotify
    - vagrant
    - virtualbox

- name: fetch dotfiles
  git:
    repo: https://github.com/joaalto/dotfiles-mac
    dest: "{{ home }}/dotfiles-mac"
